# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Webstack Hugo Theme"
license = "MIT"
licenselink = "https://github.com/iplaycode/webstack-hugo/blob/master/LICENSE"
description = "Webstack Hugo theme"
homepage = "https://github.com/iplaycode/webstack-hugo"
tags = ["startpage", "webstack", "links", "nav"]
features = []
min_version = "2.0"

[author]
  name = "iplaycode"
  homepage = "https://github.com/iplaycode/webstack-hugo"